<?php

namespace Cnes\PhileaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EtapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtapeRepository extends EntityRepository
{
}
