<?php

namespace Cnes\PhileaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProjetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetRepository extends EntityRepository {

    public function getAllUsers($idProjet) {

        $em = $this->getEntityManager();
        $query = $em->createQuery(
                "SELECT u FROM PhileaBundle:User u "
                . " JOIN u.projets p"
                . " WHERE p.id = :idp");
        $query->setParameter("idp", $idProjet);

        return $query->getResult();
    }

    public function getAllGestionnaires($idProjet) {

        $em = $this->getEntityManager();
        $query = $em->createQuery(
                "SELECT u FROM PhileaBundle:User u "
                . " JOIN u.projets p"
                . " WHERE p.id = :idp"
                . " AND u.roles LIKE '%ROLE_GESTIONNAIRE%' "
        );
        $query->setParameter("idp", $idProjet);

        return $query->getResult();
    }

    public function getAllProjets() {

        $em = $this->getEntityManager();
        $query = $em->createQuery(
                "SELECT proj, dom, eta, cla FROM PhileaBundle:Projet proj "
                . " LEFT JOIN proj.domaine dom"
                . " LEFT JOIN proj.etablissement eta"
                . " LEFT JOIN proj.classe cla"
        );

        return $query->getResult();
    }

    /**
     *  détermine si l'idEtape est une étape d'un des projets de l'utilisateur courant
     *  @param $idEtape l'étape oBjet d'un traitement d'écriture
     *  @return true si etape->project in $user->projects, false sinon
     */
    public function isEtapeInUserProjects2($idEtape, $user) {
        //$user = $this->getUser();
        // obtenir les projets de l'utilisateur
        $projets = $user->getProjets();
        //Récupère le projet selon l'étape en cours 
        $projetEtape = $this->getDoctrine()->getRepository('PhileaBundle:Etape')->find($idEtape)->getProjet();

        // l'utilisateur a-t-il le droit sur cette étape ?
        for ($i = 0; $i < count($projets); $i++) {
            if (isset($projets[$i])) {
                if ($projets[$i]->getId() == $projetEtape->getId()) {
                    return true;
                }
            }
        }
        return false;
    }

}
