# app/config/security.yml

security:
    encoders:
        Cnes\PhileaBundle\Entity\User: sha512

    role_hierarchy:
#        ROLE_ADMIN:        ROLE_USER
        ROLE_REDACTEUR:    ROLE_USER
        ROLE_GESTIONNAIRE: ROLE_REDACTEUR
        ROLE_SUPER_ADMIN:  [ROLE_GESTIONNAIRE, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: fos_user.user_provider.username


    firewalls:
        # … le pare-feu « dev »
        # Firewall principal pour le reste de notre site
        main:
            pattern:        ^/
            anonymous:      true
            provider:       main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /redacteur/
                always_use_default_target_path: true
            logout:
                path:       fos_user_security_logout
                target:     /
            remember_me:
                key:        %secret% # %secret% est un paramètre de parameters.yml

    access_control:
        - { path: ^/redacteur/, roles:[ROLE_REDACTEUR,ROLE_GESTIONNAIRE] }
        - { path: ^/gestion/, role: ROLE_GESTIONNAIRE }
        - { path: ^/register/, role: ROLE_GESTIONNAIRE }
        - { path: ^/register/confirmed, role: ROLE_SUPER_ADMIN }
        - { path: ^/ajoutArticle/, role: ROLE_GESTIONNAIRE }
        - { path: ^/gestion/utilisateurs/, roles:[ROLE_SUPER_ADMIN,ROLE_GESTIONNAIRE] }        
        - { path: ^/admin/user/, role: ROLE_SUPER_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/efconnect, role: ROLE_USER }
        - { path: ^/elfinder, role: ROLE_USER }